{
  "title": "Custom Header Modifier",
  "settings": [
    {
      "name": "headerColor",
      "title": "Header Color",
      "default": "#333",
      "type": "color"
    },
    {
      "name": "logoUrl",
      "title": "Logo Image",
      "default": "",
      "type": "upload"
    },
    {
      "name": "logoWidth",
      "title": "Logo Width",
      "default": "",
      "type": "number"
    },
    {
      "name": "logoHeight",
      "title": "Logo Height",
      "default": "",
      "type": "number"
    },
    {
      "name": "headerFont",
      "title": "Header Font",
      "default": "",
      "type": "text"
    },
    {
      "name": "headerHeight",
      "title": "Header Height",
      "default": "",
      "type": "number"
    },
    {
      "name": "headerText",
      "title": "Header Text",
      "default": "",
      "type": "text"
    },
    {
      "name": "icon1",
      "title": "Icon 1",
      "default": "",
      "type": "text"
    },
    {
      "name": "icon2",
      "title": "Icon 2",
      "default": "",
      "type": "text"
    },
    {
      "name": "icon3",
      "title": "Icon 3",
      "default": "",
      "type": "text"
    }
  ]
}
