Header_Color:
  default: "#333"
  type: color
  client: true

Logo_Image:
  default: ""
  type: upload
  client: true

Logo_Width:
  default: ""
  type: integer
  client: true

Logo_Height:
  default: ""
  type: integer
  client: true

Header_Font:
  default: ""
  type: enum
  values:
    - Arial
    - Times New Roman
    - Helvetica
    - Courier New
  client: true

Header_Height:
  default: ""
  type: integer
  client: true

Header_Text:
  default: ""
  type: text
  client: true

Icon_1:
  default: ""
  type: text
  client: true

Icon_2:
  default: ""
  type: text
  client: true

Icon_3:
  default: ""
  type: text
  client: true
